showVerionsTab: true
showEnvVarsTab: true
allowAutoApplyLimits: false
name: U-store
title: U-store
logo: https://localhost.unifie.cloud/branding/headerLogo.svg
tags: ""
description: U-store
oneDeploymentPerCluster: false
notAllowRemoveNamespace: false
autoAddEnvVarsToDeployments: true
