showVerionsTab: true
showEnvVarsTab: true
allowAutoApplyLimits: false
name: U-store
title: U-store
logo: null
tags: ""
description: U-store
oneDeploymentPerCluster: false
notAllowRemoveNamespace: false
autoAddEnvVarsToDeployments: true
